### PR TITLE
add homepage 'Join as a mentor' CTA with basic card styles

### PR DESCRIPTION
**Pull request by lilyndk**
## Description
Homepage section updates:
- add second 'Join as mentor' CTA
- add simple card styles to both CTAs in the row
- remove unused home styles
- refactor and remove style classes from html to reduce file size
- create max-width container variable

## Change Type
- [ ] Bug Fix
- [X] New Feature
- [ ] Code Refactor
- [ ] Mentor Update
- [ ] Documentation
- [ ] Other

## Related Issue
https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/74

## Screenshots
AFTER:
Screenshot 2024-04-25 at 14 04 44

BEFORE:
Screenshot 2024-04-25 at 14 06 25

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] I checked and followed the [contributor guide](CONTRIBUTING.md) 
- [X] I have tested my changes locally.
- [X] I have added a screenshot from the website after I tested it locally

### CODE REVIEW

**Comment by lilyndk** [comment]
@nverbic You might want to reuse some of these basic 'bootstrap card styles/markup' in your work on https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/77 :) I think that will make it easier to fix the alignment issue as well.

**Comment by lilyndk** [comment]
@dricazenck I added the text for the new CTA, so just let me know if that needs to change :)

**Comment by nverbic** [comment]
Looks nice! 👌✨

**Review by dricazenck — APPROVED** [review]
🚀

**Pull request merged**
