### PR TITLE
book club add what we are reading page

### PR DESCRIPTION
**Pull request by parisa-0**
## Description
 

Added a section in book club page on what we are reading
https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/95

## Change Type
- [X] Bug Fix
- [ ] New Feature
- [ ] Code Refactor
- [ ] Mentor Update
- [ ] Documentation
- [ ] Other

## Related Issue

https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/95

## Screenshots

Before:
image

After:
image

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] I checked and followed the [contributor guide](CONTRIBUTING.md) 
- [X] I have tested my changes locally.
- [X] I have added a screenshot from the website after I tested it locally

### CODE REVIEW

**Review by mads6879 — APPROVED** [review]

**Review by khairahscorner — CHANGES_REQUESTED** [review]
@parisa-0 could you consider using this layout below? I think it makes it look more visual so, we'd have:
- the head text as the book title,
- the sub text underneath could changed to **"Author(s): <<their names>>"**,
- the summary as the book excerpt,
- the image could be a picture of the book instead
- the social media icons can be replaced with a website icon that links to maybe a shop that readers can buy the book from

The code for the layout can be found **[here](https://github.com/WomenWhoCode/london/blob/main/resources.html#:~:text=%3Ch2%3EEvents%3C/h2%3E)**😊

Screenshot 2024-04-27 at 7 02 37 am

@dricazenck what do you think?

**Comment by lilyndk** [comment]
@khairahscorner I suggest we merge these this approved PR. And then create a separate PR / new ticket for this 'card styling' feature request :)

**Comment by khairahscorner** [comment]
sounds like a good idea 👍 @lilyndk

**Review by khairahscorner — APPROVED** [review]

**Comment by dricazenck** [comment]
That page as I mentioned should be created dynamic. This should not be hardcoded. It should be done as mentors, resources and team. Because makes way easier for us to add more books. But let's fix that in another pr.

**Comment by parisa-0** [comment]
Hi thank you both for your feedback, I've created #108 to look at implementing this with card style feature and the ability to add the books more dynamically :)

**Comment by lilyndk** [comment]
@parisa-0 Fyi, @khairahscorner is currently working on the blog https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/98 with incorporated card styles. So perhaps wait for that to be done before adding more card styles, since it's best that we just reuse those card styles :)

**Pull request merged**
