### PR TITLE
Update blog with TechCrunch Disrupt Learnings

### PR DESCRIPTION
**Pull request by Amenawon**
## Description
 

Update blog with TechCrunch Disrupt Learnings 

## Change Type
- [ ] Bug Fix
- [ ] New Feature
- [ ] Code Refactor
- [ ] Mentor Update
- [X] Data Update
- [ ] Documentation
- [ ] Other

## Related Issue

https://github.com/Women-Coding-Community/WomenCodingCommunity.github.io/issues/390

## Screenshots

Screenshot 2024-12-18 at 19 56 19
Screenshot 2024-12-18 at 19 56 53
Screenshot 2024-12-18 at 19 57 16

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] I checked and followed the [contributor guide](CONTRIBUTING.md) 
- [X] I have tested my changes locally.
- [X] I have added a screenshot from the website after I tested it locally

### CODE REVIEW

**Review by dricazenck — COMMENTED** [review]
Could please ajudar the image size? It is 2.1mb that is too big, anything around 300kb is ok

**Comment by dricazenck** [comment]
Also the title is the pull request is not correct. Could you update as well.

**Comment by Amenawon** [comment]
> Could please ajudar the image size? It is 2.1mb that is too big, anything around 300kb is ok

Done!

**Comment by Amenawon** [comment]
> Also the title is the pull request is not correct. Could you update as well.

done!

**Review by dricazenck — APPROVED** [review]

**Pull request merged**
