### PR TITLE
PR - Add Mentorship Resources page - inital version

### PR DESCRIPTION
**Pull request by nverbic**
## Description

Add initial version of the Mentorship Resources page.
Add minimal styling (from old resources style)
Add resources.yml without images and links

## Change Type
- [ ] Bug Fix
- [x] New Feature
- [ ] Code Refactor
- [ ] Mentor Update
- [ ] Documentation
- [ ] Other

## Related Issue
(https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/27)

## Screenshots

Before
image

After

resources_aligned

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] I checked and followed the [contributor guide](CONTRIBUTING.md) 
- [x] I have tested my changes locally.
- [x] I have added a screenshot from the website after I tested it locally

### CODE REVIEW

**Comment by nverbic** [comment]
For now, I haven't added any links to the yml file. If you agree to use some links, I can add them later.

**Comment by dricazenck** [comment]
Looks good to me, let's just wait for the links and images. I think Sonali will have that soon.

**Comment by nverbic** [comment]
Great! Ok :-)

**Comment by goelsonali** [comment]
Link for the Mentor's Guide - https://drive.google.com/file/d/1-2aXUJaLc-pYNTWTiM2ZugW7IDtd3my0/view
Link for the Mentee's Guide - https://drive.google.com/file/d/1QfM-zCk-_LSR8rrfrawyog-bM_n7BFbG/view

**Comment by goelsonali** [comment]
Mentor's pocket book new link - https://drive.google.com/file/d/1rgoOTqqG4Gu6e4tw45efFspDnoYRgYd9/view

**Comment by goelsonali** [comment]
I am not sure about the images for the front-end. We might need some new design or can be without images not sure.

**Comment by nverbic** [comment]
Thank you @goelsonali - I will add them now. 👌

**Comment by nverbic** [comment]
I have added the links above and the resources are center aligned. The updated image is in the description of the issue.

**Review by dricazenck — APPROVED** [review]

**Pull request merged**
